package com.msa.playback360
import java.io.File
data class CodeModel360(val identity:String,val regions:Int,val highEntropy:Int,val textEvidence:Int,val semanticEvidence:Int,val numericCandidates:Int,val verified:Int,val uncertain:Int)
object CodeDeepDive360 {
 fun model(file:File,r:MqlBinaryReport360):CodeModel360{val s=ExStructure360.inspect(file);val n=NumericEvidenceScanner360.scan(file);val sem=r.evidence.count{it.kind in setOf(MqlObjectKind.MQL_EVENT,MqlObjectKind.TRADING_API,MqlObjectKind.INDICATOR,MqlObjectKind.DLL,MqlObjectKind.URL)};val v=r.evidence.count{it.confidence>=90};return CodeModel360(r.kind.toString()+":"+r.fileName,s.regions.size,s.regions.count{it.label=="HIGH_ENTROPY"},r.strings,sem,n.size,v,r.evidence.size-v)}
 fun renderModel(m:CodeModel360)="CODE MODEL\n"+m.identity+"\nRegions: "+m.regions+"\nHigh entropy: "+m.highEntropy+"\nText evidence: "+m.textEvidence+"\nSemantic evidence: "+m.semanticEvidence+"\nNumeric candidates: "+m.numericCandidates+"\nHigh-confidence evidence: "+m.verified+"\nUncertain evidence: "+m.uncertain
 fun evidence(r:MqlBinaryReport360)=r.evidence.sortedWith(compareByDescending<MqlEvidence360>{it.confidence}.thenBy{it.offset?:Long.MAX_VALUE})
 fun verify(file:File,r:MqlBinaryReport360):String{val s=ExStructure360.inspect(file);val p=mutableListOf<String>();if(r.size!=file.length())p+="Reported size differs from file size.";if(r.sha256.length!=64)p+="SHA-256 identity is invalid.";val bad=r.evidence.count{it.offset!=null&&(it.offset<0||it.offset>=r.size)};if(bad>0)p+=bad.toString()+" evidence offsets are outside file bounds.";return "VERIFY\nIdentity: "+if(p.isEmpty())"PASS\nSHA-256: "+r.sha256+"\nEvidence offsets checked: "+r.evidence.size+"\nHigh-entropy regions: "+s.regions.count{it.label=="HIGH_ENTROPY"}+"/"+s.regions.size+"\nNo structural consistency errors detected.\n\nVerification confirms evidence consistency only; it does not prove recovery of original source." else "CHECK\n"+p.joinToString("\n")}
 fun extract(file:File,r:MqlBinaryReport360)=renderModel(model(file,r))+"\n\nEXTRACTOR LAYERS\n1 identity/hash\n2 region statistics\n3 ASCII/Unicode evidence\n4 numeric candidates\n5 MQL semantic classification\n6 DLL/URL references\n7 offset/proximity relationships\n8 reconstructed source model"
 fun cli()="MQL360 COMMAND PIPELINE\n/codebase\n/codeextractor\n/codemodel\n/codeevidence\n/codeverify\n/codenumeric\n/codeunicode\n/structure\n/codereconstruct mq4|mq5\n/codegrep <text>\n/codeoffset <0xOFFSET>\n/coderelated <text>\n/code*\n\nAll operations are read-only analysis; reconstruction is evidence-backed."
 fun catalog()=(MqlCodeLibrary360.commands.map{it.command+"  ["+it.domain+"] "+it.action}+listOf("/codebase","/codeextractor","/codemodel","/codeevidence","/codeverify","/codecli","/codeconstants","/codenumeric","/codestructure","/coderegions","/codereconstruct","/codecompare","/codediff")).distinct().sorted().joinToString("\n")
}
